### PR TITLE
CC-46 Changes for new component multi select without group

### PR DESCRIPTION
**Pull request by Dharmik-atharva**
(https://github.com/Components-care/backlog/issues/46)

- Extracted autocomplete part from MultiSelectWithTags and created new component.
- Used new component in MultiSelectWithTags.
- Created story for MultiSelectWithoutGroup

### CODE REVIEW

**Review by TQjona — CHANGES_REQUESTED** [review]
Selected Group logic should remain in MultiSelectWithTags.
You can implement the logic for unsetting selected groups by checking if an item that was part of a selected group is no longer selected.
```tsx
	setSelectedGroups((oldSelectedGroups) =>
		oldSelectedGroups.filter(
			(group) => !group.items.find((item) => !selectedIds.includes(item))
		)
	);
```

**Comment by TQjona** [comment]
Also the interface SelectedGroup should stay in MultiSelectWithTags and there should be a subClasses prop in MultiSelectWithTags so I can style the MultiSelectWithoutGroup component

**Comment by Dharmik-atharva** [comment]
@TQjona , Requested changes done. Please review

**Review by TQjona — CHANGES_REQUESTED** [review]

**Comment by Dharmik-atharva** [comment]
@TQjona , Requested Changes done. Please review

**Review by TQjona — APPROVED** [review]

**Pull request merged**
