### PR TITLE
[CC-37] (https://github.com/Components-care/backlog/issues/37) Change…

### PR DESCRIPTION
**Pull request by Dharmik-atharva**
(https://github.com/Components-care/backlog/issues/37)

- Add avatar class to limit image size to its parent container

### CODE REVIEW

**Review by TQjona — CHANGES_REQUESTED** [review]
Doing some changes to CSS...
image

results in this
image

also image should be below button and have padding

**Review by TQjona — CHANGES_REQUESTED** [review]
now it doesn't scale up anymore when i remove the height limit...
suggestion: unset `width: auto` and set `object-fit: contain` instead.
And move these styles to the image selector. I only want to have to set width and height of the grid item wrapping the image selector

**Comment by Dharmik-atharva** [comment]
@TQjona , Suggested changes done, Please review

**Comment by TQjona** [comment]
you moved yourself back to square one with your last commit. so i fixed it for you.

**Review by TQjona — APPROVED** [review]

**Review by ankitp-atharva — APPROVED** [review]

**Pull request merged**
